import type { Course } from "@/types/Courses"
// Interface for pagination results
export interface PaginatedCourses {
  courses: Course[]
  totalCourses: number
  totalPages: number
  currentPage: number
}

// This is a server-side function to fetch courses with pagination
export async function getCourses(page = 1, limit = 10): Promise<PaginatedCourses> {
  // In a real application, you would fetch from your database or API
  // For now, we'll return mock data

  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 1000))

  // Calculate pagination
  const startIndex = (page - 1) * limit
  const endIndex = startIndex + limit
  const paginatedCourses = mockCourses.slice(startIndex, endIndex)
  const totalPages = Math.ceil(mockCourses.length / limit)

  return {
    courses: paginatedCourses,
    totalCourses: mockCourses.length,
    totalPages,
    currentPage: page,
  }
}

// Function to get a course by ID
export async function getCourseById(id: string): Promise<Course | undefined> {
  // In a real application, you would fetch from your database or API
  // For now, we'll return mock data

  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 1000))

  return mockCourses.find((course) => course._id === id)
}

// Generate more mock data for pagination demonstration
const mockCourses: Course[] = [
  {
    _id: "1",
    name: "Lập trình JavaScript cơ bản đến nâng cao",
    description:
      "Khóa học toàn diện về JavaScript từ cơ bản đến nâng cao, bao gồm ES6+, DOM, Async/Await và các framework phổ biến.",
    image: "/images/Courses.jpg",
    price: 1200000,
    discount: 15,
    category: "Lập trình Web",
    status: true,
    teacherId: {
      _id: "t1",
      firstName: "Nguyễn",
      lastName: "Văn A",
      address: "Hà Nội",
      avartar: "/images/avatar.png",
      email: "nguyenvana@example.com",
      role: "Giảng viên chính",
      major: [
        { name: "JavaScript", color: "#f7df1e" },
        { name: "React", color: "#61dafb" },
      ],
      educationLevel: "Thạc sĩ",
      experienceYears: 5,
      publications: ["JavaScript Modern", "React Best Practices"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "2",
    name: "Thiết kế UI/UX chuyên nghiệp",
    description:
      "Học cách thiết kế giao diện người dùng đẹp mắt và trải nghiệm người dùng tối ưu với các công cụ hiện đại.",
    image: "/images/Courses.jpg",
    price: 1500000,
    discount: 0,
    category: "Thiết kế",
    status: true,
    teacherId: {
      _id: "t2",
      firstName: "Trần",
      lastName: "Thị B",
      address: "TP. Hồ Chí Minh",
      avartar: "/images/avatar.png",
      email: "tranthib@example.com",
      role: "Chuyên gia UI/UX",
      major: [
        { name: "Figma", color: "#a259ff" },
        { name: "Adobe XD", color: "#ff61f6" },
      ],
      educationLevel: "Cử nhân",
      experienceYears: 7,
      publications: ["UX Research Methods"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "3",
    name: "Machine Learning và AI cơ bản",
    description: "Tìm hiểu về các thuật toán Machine Learning và ứng dụng AI trong thực tế với Python và TensorFlow.",
    image: "/images/Courses.jpg",
    price: 2000000,
    discount: 10,
    category: "AI & Data Science",
    status: false,
    teacherId: {
      _id: "t3",
      firstName: "Lê",
      lastName: "Văn C",
      address: "Đà Nẵng",
      avartar: "/images/avatar.png",
      email: "levanc@example.com",
      role: "Tiến sĩ AI",
      major: [
        { name: "Python", color: "#3776ab" },
        { name: "TensorFlow", color: "#ff6f00" },
        { name: "Data Science", color: "#21a366" },
      ],
      educationLevel: "Tiến sĩ",
      experienceYears: 10,
      publications: ["Deep Learning Applications", "Neural Networks in Practice"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "4",
    name: "Phát triển ứng dụng di động với React Native",
    description: "Xây dựng ứng dụng di động đa nền tảng với React Native, Redux và các thư viện phổ biến.",
    image: "/images/Courses.jpg",
    price: 1800000,
    discount: 20,
    category: "Lập trình Mobile",
    status: true,
    teacherId: {
      _id: "t1",
      firstName: "Nguyễn",
      lastName: "Văn A",
      address: "Hà Nội",
      avartar: "/images/avatar.png",
      email: "nguyenvana@example.com",
      role: "Giảng viên chính",
      major: [
        { name: "JavaScript", color: "#f7df1e" },
        { name: "React", color: "#61dafb" },
        { name: "React Native", color: "#61dafb" },
      ],
      educationLevel: "Thạc sĩ",
      experienceYears: 5,
      publications: ["JavaScript Modern", "React Best Practices"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "5",
    name: "DevOps và CI/CD cho dự án phần mềm",
    description: "Học cách triển khai quy trình DevOps, tự động hóa CI/CD và quản lý hạ tầng với Docker và Kubernetes.",
    image: "/images/Courses.jpg",
    price: 2200000,
    discount: 5,
    category: "DevOps",
    status: true,
    teacherId: {
      _id: "t4",
      firstName: "Phạm",
      lastName: "Văn D",
      address: "Hà Nội",
      avartar: "/images/avatar.png",
      email: "phamvand@example.com",
      role: "DevOps Engineer",
      major: [
        { name: "Docker", color: "#2496ed" },
        { name: "Kubernetes", color: "#326ce5" },
        { name: "AWS", color: "#ff9900" },
      ],
      educationLevel: "Thạc sĩ",
      experienceYears: 8,
      publications: ["Cloud Native Applications"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "6",
    name: "Lập trình Backend với Node.js và Express",
    description: "Xây dựng API RESTful và ứng dụng web server-side với Node.js, Express và MongoDB.",
    image: "/images/Courses.jpg",
    price: 1600000,
    discount: 0,
    category: "Lập trình Web",
    status: true,
    teacherId: {
      _id: "t5",
      firstName: "Hoàng",
      lastName: "Thị E",
      address: "TP. Hồ Chí Minh",
      avartar: "/images/avatar.png",
      email: "hoangthie@example.com",
      role: "Backend Developer",
      major: [
        { name: "Node.js", color: "#339933" },
        { name: "MongoDB", color: "#47a248" },
        { name: "Express", color: "#000000" },
      ],
      educationLevel: "Cử nhân",
      experienceYears: 6,
      publications: [],
      isActive: true,
      isClose: false,
    },
  },
  // Thêm nhiều khóa học hơn để demo phân trang
  {
    _id: "7",
    name: "Lập trình Python cho người mới bắt đầu",
    description: "Học lập trình Python từ cơ bản đến nâng cao với các ví dụ thực tế và dự án thực hành.",
    image: "/images/Courses.jpg",
    price: 1400000,
    discount: 10,
    category: "Lập trình",
    status: true,
    teacherId: {
      _id: "t3",
      firstName: "Lê",
      lastName: "Văn C",
      address: "Đà Nẵng",
      avartar: "/images/avatar.png",
      email: "levanc@example.com",
      role: "Tiến sĩ AI",
      major: [
        { name: "Python", color: "#3776ab" },
        { name: "Data Science", color: "#21a366" },
      ],
      educationLevel: "Tiến sĩ",
      experienceYears: 10,
      publications: ["Python for Beginners"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "8",
    name: "Thiết kế đồ họa với Adobe Photoshop",
    description: "Khóa học toàn diện về thiết kế đồ họa sử dụng Adobe Photoshop từ cơ bản đến nâng cao.",
    image: "/images/Courses.jpg",
    price: 1300000,
    discount: 15,
    category: "Thiết kế",
    status: true,
    teacherId: {
      _id: "t2",
      firstName: "Trần",
      lastName: "Thị B",
      address: "TP. Hồ Chí Minh",
      avartar: "/images/avatar.png",
      email: "tranthib@example.com",
      role: "Chuyên gia UI/UX",
      major: [
        { name: "Photoshop", color: "#31A8FF" },
        { name: "Graphic Design", color: "#FF61F6" },
      ],
      educationLevel: "Cử nhân",
      experienceYears: 7,
      publications: ["Photoshop Masterclass"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "9",
    name: "Lập trình iOS với Swift",
    description: "Học cách phát triển ứng dụng iOS sử dụng ngôn ngữ Swift và SwiftUI framework.",
    image: "/images/Courses.jpg",
    price: 2100000,
    discount: 0,
    category: "Lập trình Mobile",
    status: true,
    teacherId: {
      _id: "t6",
      firstName: "Vũ",
      lastName: "Minh F",
      address: "Hà Nội",
      avartar: "/images/avatar.png",
      email: "vuminhf@example.com",
      role: "iOS Developer",
      major: [
        { name: "Swift", color: "#F05138" },
        { name: "iOS", color: "#000000" },
      ],
      educationLevel: "Thạc sĩ",
      experienceYears: 6,
      publications: ["Swift Programming Guide"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "10",
    name: "Lập trình game với Unity",
    description: "Học cách phát triển game 2D và 3D sử dụng Unity Engine và C#.",
    image: "/images/Courses.jpg",
    price: 1900000,
    discount: 5,
    category: "Game Development",
    status: true,
    teacherId: {
      _id: "t7",
      firstName: "Đỗ",
      lastName: "Văn G",
      address: "TP. Hồ Chí Minh",
      avartar: "/images/avatar.png",
      email: "dovang@example.com",
      role: "Game Developer",
      major: [
        { name: "Unity", color: "#000000" },
        { name: "C#", color: "#512BD4" },
      ],
      educationLevel: "Cử nhân",
      experienceYears: 5,
      publications: ["Game Development with Unity"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "11",
    name: "Lập trình Blockchain và Smart Contracts",
    description: "Tìm hiểu về công nghệ Blockchain và cách phát triển Smart Contracts với Solidity.",
    image: "/images/Courses.jpg",
    price: 2500000,
    discount: 0,
    category: "Blockchain",
    status: true,
    teacherId: {
      _id: "t8",
      firstName: "Ngô",
      lastName: "Thị H",
      address: "Hà Nội",
      avartar: "/images/avatar.png",
      email: "ngothih@example.com",
      role: "Blockchain Developer",
      major: [
        { name: "Blockchain", color: "#F7931A" },
        { name: "Solidity", color: "#363636" },
      ],
      educationLevel: "Tiến sĩ",
      experienceYears: 4,
      publications: ["Blockchain Fundamentals"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "12",
    name: "Thiết kế 3D với Blender",
    description: "Học cách tạo mô hình 3D, animation và rendering với phần mềm Blender.",
    image: "/images/Courses.jpg",
    price: 1700000,
    discount: 10,
    category: "Thiết kế",
    status: true,
    teacherId: {
      _id: "t9",
      firstName: "Lý",
      lastName: "Văn I",
      address: "Đà Nẵng",
      avartar: "/images/avatar.png",
      email: "lyvani@example.com",
      role: "3D Artist",
      major: [
        { name: "Blender", color: "#F5792A" },
        { name: "3D Modeling", color: "#7C4DFF" },
      ],
      educationLevel: "Cử nhân",
      experienceYears: 7,
      publications: ["3D Design with Blender"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "13",
    name: "Digital Marketing toàn diện",
    description: "Học các kỹ thuật marketing online, SEO, quảng cáo Google và Facebook, email marketing.",
    image: "/images/Courses.jpg",
    price: 1600000,
    discount: 20,
    category: "Marketing",
    status: true,
    teacherId: {
      _id: "t10",
      firstName: "Trịnh",
      lastName: "Thị K",
      address: "TP. Hồ Chí Minh",
      avartar: "/images/avatar.png",
      email: "trinhthik@example.com",
      role: "Marketing Specialist",
      major: [
        { name: "Digital Marketing", color: "#4285F4" },
        { name: "SEO", color: "#34A853" },
      ],
      educationLevel: "Thạc sĩ",
      experienceYears: 8,
      publications: ["Digital Marketing Strategies"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "14",
    name: "Quản lý dự án với Agile và Scrum",
    description: "Học cách quản lý dự án hiệu quả với phương pháp Agile và framework Scrum.",
    image: "/images/Courses.jpg",
    price: 1800000,
    discount: 5,
    category: "Quản lý",
    status: true,
    teacherId: {
      _id: "t11",
      firstName: "Phùng",
      lastName: "Văn L",
      address: "Hà Nội",
      avartar: "/images/avatar.png",
      email: "phungvanl@example.com",
      role: "Project Manager",
      major: [
        { name: "Agile", color: "#6DB33F" },
        { name: "Scrum", color: "#009FDA" },
      ],
      educationLevel: "Thạc sĩ",
      experienceYears: 10,
      publications: ["Agile Project Management"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "15",
    name: "Lập trình Embedded Systems",
    description: "Học cách phát triển phần mềm cho hệ thống nhúng với Arduino và Raspberry Pi.",
    image: "/images/Courses.jpg",
    price: 2000000,
    discount: 0,
    category: "Lập trình",
    status: false,
    teacherId: {
      _id: "t12",
      firstName: "Đinh",
      lastName: "Văn M",
      address: "Đà Nẵng",
      avartar: "/images/avatar.png",
      email: "dinhvanm@example.com",
      role: "Embedded Engineer",
      major: [
        { name: "Arduino", color: "#00979D" },
        { name: "Raspberry Pi", color: "#C51A4A" },
      ],
      educationLevel: "Tiến sĩ",
      experienceYears: 9,
      publications: ["Embedded Systems Programming"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "16",
    name: "Phân tích dữ liệu với Python",
    description: "Học cách phân tích và trực quan hóa dữ liệu sử dụng Python, Pandas và Matplotlib.",
    image: "/images/Courses.jpg",
    price: 1700000,
    discount: 15,
    category: "Data Science",
    status: true,
    teacherId: {
      _id: "t3",
      firstName: "Lê",
      lastName: "Văn C",
      address: "Đà Nẵng",
      avartar: "/images/avatar.png",
      email: "levanc@example.com",
      role: "Tiến sĩ AI",
      major: [
        { name: "Python", color: "#3776AB" },
        { name: "Data Analysis", color: "#21A366" },
      ],
      educationLevel: "Tiến sĩ",
      experienceYears: 10,
      publications: ["Data Analysis with Python"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "17",
    name: "Lập trình Web với PHP và Laravel",
    description: "Học cách phát triển ứng dụng web sử dụng PHP và framework Laravel.",
    image: "/images/Courses.jpg",
    price: 1500000,
    discount: 10,
    category: "Lập trình Web",
    status: true,
    teacherId: {
      _id: "t13",
      firstName: "Bùi",
      lastName: "Thị N",
      address: "TP. Hồ Chí Minh",
      avartar: "/images/avatar.png",
      email: "buithin@example.com",
      role: "Web Developer",
      major: [
        { name: "PHP", color: "#777BB4" },
        { name: "Laravel", color: "#FF2D20" },
      ],
      educationLevel: "Cử nhân",
      experienceYears: 6,
      publications: ["Laravel Web Development"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "18",
    name: "Thiết kế UX Research",
    description: "Học cách thực hiện nghiên cứu người dùng và áp dụng kết quả vào thiết kế sản phẩm.",
    image: "/images/Courses.jpg",
    price: 1900000,
    discount: 0,
    category: "Thiết kế",
    status: true,
    teacherId: {
      _id: "t2",
      firstName: "Trần",
      lastName: "Thị B",
      address: "TP. Hồ Chí Minh",
      avartar: "/images/avatar.png",
      email: "tranthib@example.com",
      role: "Chuyên gia UI/UX",
      major: [
        { name: "UX Research", color: "#A259FF" },
        { name: "User Testing", color: "#FF61F6" },
      ],
      educationLevel: "Cử nhân",
      experienceYears: 7,
      publications: ["UX Research Methods"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "19",
    name: "Lập trình Android với Kotlin",
    description: "Học cách phát triển ứng dụng Android sử dụng ngôn ngữ Kotlin và Jetpack Compose.",
    image: "/images/Courses.jpg",
    price: 2000000,
    discount: 5,
    category: "Lập trình Mobile",
    status: true,
    teacherId: {
      _id: "t14",
      firstName: "Dương",
      lastName: "Văn O",
      address: "Hà Nội",
      avartar: "/images/avatar.png",
      email: "duongvano@example.com",
      role: "Android Developer",
      major: [
        { name: "Kotlin", color: "#7F52FF" },
        { name: "Android", color: "#3DDC84" },
      ],
      educationLevel: "Thạc sĩ",
      experienceYears: 7,
      publications: ["Android Development with Kotlin"],
      isActive: true,
      isClose: false,
    },
  },
  {
    _id: "20",
    name: "Lập trình Fullstack với MERN Stack",
    description: "Học cách phát triển ứng dụng web fullstack với MongoDB, Express, React và Node.js.",
    image: "/images/Courses.jpg",
    price: 2200000,
    discount: 10,
    category: "Lập trình Web",
    status: true,
    teacherId: {
      _id: "t15",
      firstName: "Hoàng",
      lastName: "Văn P",
      address: "TP. Hồ Chí Minh",
      avartar: "/images/avatar.png",
      email: "hoangvanp@example.com",
      role: "Fullstack Developer",
      major: [
        { name: "React", color: "#61DAFB" },
        { name: "Node.js", color: "#339933" },
        { name: "MongoDB", color: "#47A248" },
      ],
      educationLevel: "Cử nhân",
      experienceYears: 5,
      publications: ["MERN Stack Development"],
      isActive: true,
      isClose: false,
    },
  },
]

